package com.kylin.skinlibrary.utils

/**
 * @Description:
 * @Auther: wangqi
 * CreateTime: 2020/8/4.
 */
object SystemViewName {
    const val FRAGMENT_CONTAINER_VIEW = "androidx.fragment.app.FragmentContainerView"
    const val NESTED_SCROLL_VIEW = "androidx.core.widget.NestedScrollView"
    const val APPCOMPAT_EDIT_TEXT = "androidx.appcompat.widget.AppCompatEditText"
    const val MATERIAL_BUTTON = "com.google.android.material.button.MaterialButton"
    const val FRAGMENT = "fragment"
    const val LINEAR_LAYOUT = "LinearLayout"
    const val LINEAR_LAYOUT_COMPAT = "androidx.appcompat.widget.LinearLayoutCompat"
    const val CONSTRAINT_LAYOUT = "androidx.constraintlayout.widget.ConstraintLayout"
    const val RELATIVE_LAYOUT = "RelativeLayout"
    const val TEXT_VIEW = "TextView"
    const val IMAGE_VIEW = "ImageView"
    const val BUTTON = "Button"
    const val EDIT_TEXT = "EditText"
    const val FRAME_LAYOUT = "FrameLayout"
    const val SCROLL_VIEW = "ScrollView"
    const val CARD_VIEW = "androidx.cardview.widget.CardView"
    const val MATERIAL_CARD_VIEW = "com.google.android.material.card.MaterialCardView"
    const val VIEW = "View"
    const val IMAGE_BUTTON = "ImageButton"
    const val CHECK_BOX = "CheckBox"
    const val RADIO_BUTTON = "RadioButton"
    const val SWITCH = "Switch"
    const val SWITCH_COMPAT = "androidx.appcompat.widget.SwitchCompat"
    const val TOGGLE_BUTTON = "ToggleButton"
    const val CHECKED_TEXT_VIEW = "CheckedTextView"
    const val AUTO_COMPLETE_TEXT_VIEW = "AutoCompleteTextView"
    const val APPCOMPAT_AUTO_COMPLETE_TEXT_VIEW = "androidx.appcompat.widget.AppCompatAutoCompleteTextView"
    const val TAB_LAYOUT = "com.google.android.material.tabs.TabLayout"
    const val RECYCLER_VIEW = "androidx.recyclerview.widget.RecyclerView"
    const val VIEW_PAGER = "androidx.viewpager.widget.ViewPager"
    const val HORIZONTAL_SCROLL_VIEW = "HorizontalScrollView"
    const val SHAPEABLE_IMAGE_VIEW = "com.google.android.material.imageview.ShapeableImageView"
    const val TEXT_SWITCHER = "TextSwitcher"
    const val VIEW_SWITCHER = "ViewSwitcher"
    const val VIEW_FLIPPER = "ViewFlipper"
    const val PROGRESS_BAR = "ProgressBar"
    const val SEEK_BAR = "SeekBar"
    const val RATING_BAR = "RatingBar"
    const val RADIO_GROUP = "RadioGroup"
    const val SPINNER = "Spinner"
    const val LIST_VIEW = "ListView"
    const val GRID_VIEW = "GridView"
    const val EXPANDABLE_LIST_VIEW = "ExpandableListView"
    const val GRID_LAYOUT = "GridLayout"
    const val TABLE_LAYOUT = "TableLayout"
    const val MULTI_AUTO_COMPLETE_TEXT_VIEW = "MultiAutoCompleteTextView"
    const val TEXT_CLOCK = "TextClock"
    const val COORDINATOR_LAYOUT = "androidx.coordinatorlayout.widget.CoordinatorLayout"
    const val APP_BAR_LAYOUT = "com.google.android.material.appbar.AppBarLayout"
    const val COLLAPSING_TOOLBAR_LAYOUT = "com.google.android.material.appbar.CollapsingToolbarLayout"
    const val DRAWER_LAYOUT = "androidx.drawerlayout.widget.DrawerLayout"
    const val TOOLBAR = "androidx.appcompat.widget.Toolbar"
    const val BOTTOM_NAVIGATION_VIEW = "com.google.android.material.bottomnavigation.BottomNavigationView"
    const val FLOATING_ACTION_BUTTON = "com.google.android.material.floatingactionbutton.FloatingActionButton"
    const val CHIP = "com.google.android.material.chip.Chip"
    const val CHIP_GROUP = "com.google.android.material.chip.ChipGroup"
    const val TEXT_INPUT_LAYOUT = "com.google.android.material.textfield.TextInputLayout"
    const val TEXT_INPUT_EDIT_TEXT = "com.google.android.material.textfield.TextInputEditText"
    const val MATERIAL_DIVIDER = "com.google.android.material.divider.MaterialDivider"
}